/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: this file is normally auto-generated by `next dev`/`next build` on
// first run. It's committed here (empty of custom content, just the
// reference triple-slash directives Next itself would write) purely so
// `tsc --noEmit` / editors have the ambient types available before anyone
// has run `npm run dev` once. Do not edit by hand beyond this.
