-- 0014_seed_provinces.sql
-- Seed all 77 Thai provinces into analytics.dim_geo with ISO 3166-2:TH codes,
-- Thai + English names, and region grouping. Idempotent (upsert on province_code).
-- TH-XX ("ไม่ทราบจังหวัด", is_unknown=true) is seeded by 0010; not repeated here.
-- Applied to DB via MCP 2026-08-10; backfilled to repo 2026-08-11.

insert into analytics.dim_geo (province_code, province_name_th, province_name_en, region, is_unknown) values
('TH-10','กรุงเทพมหานคร','Bangkok','bkk_metro',false),
('TH-11','สมุทรปราการ','Samut Prakan','bkk_metro',false),
('TH-12','นนทบุรี','Nonthaburi','bkk_metro',false),
('TH-13','ปทุมธานี','Pathum Thani','bkk_metro',false),
('TH-73','นครปฐม','Nakhon Pathom','bkk_metro',false),
('TH-74','สมุทรสาคร','Samut Sakhon','bkk_metro',false),
('TH-14','พระนครศรีอยุธยา','Phra Nakhon Si Ayutthaya','central',false),
('TH-15','อ่างทอง','Ang Thong','central',false),
('TH-16','ลพบุรี','Lop Buri','central',false),
('TH-17','สิงห์บุรี','Sing Buri','central',false),
('TH-18','ชัยนาท','Chai Nat','central',false),
('TH-19','สระบุรี','Saraburi','central',false),
('TH-26','นครนายก','Nakhon Nayok','central',false),
('TH-60','นครสวรรค์','Nakhon Sawan','central',false),
('TH-61','อุทัยธานี','Uthai Thani','central',false),
('TH-62','กำแพงเพชร','Kamphaeng Phet','central',false),
('TH-64','สุโขทัย','Sukhothai','central',false),
('TH-65','พิษณุโลก','Phitsanulok','central',false),
('TH-66','พิจิตร','Phichit','central',false),
('TH-67','เพชรบูรณ์','Phetchabun','central',false),
('TH-72','สุพรรณบุรี','Suphan Buri','central',false),
('TH-75','สมุทรสงคราม','Samut Songkhram','central',false),
('TH-20','ชลบุรี','Chon Buri','east',false),
('TH-21','ระยอง','Rayong','east',false),
('TH-22','จันทบุรี','Chanthaburi','east',false),
('TH-23','ตราด','Trat','east',false),
('TH-24','ฉะเชิงเทรา','Chachoengsao','east',false),
('TH-25','ปราจีนบุรี','Prachin Buri','east',false),
('TH-27','สระแก้ว','Sa Kaeo','east',false),
('TH-30','นครราชสีมา','Nakhon Ratchasima','northeast',false),
('TH-31','บุรีรัมย์','Buri Ram','northeast',false),
('TH-32','สุรินทร์','Surin','northeast',false),
('TH-33','ศรีสะเกษ','Si Sa Ket','northeast',false),
('TH-34','อุบลราชธานี','Ubon Ratchathani','northeast',false),
('TH-35','ยโสธร','Yasothon','northeast',false),
('TH-36','ชัยภูมิ','Chaiyaphum','northeast',false),
('TH-37','อำนาจเจริญ','Amnat Charoen','northeast',false),
('TH-38','บึงกาฬ','Bueng Kan','northeast',false),
('TH-39','หนองบัวลำภู','Nong Bua Lam Phu','northeast',false),
('TH-40','ขอนแก่น','Khon Kaen','northeast',false),
('TH-41','อุดรธานี','Udon Thani','northeast',false),
('TH-42','เลย','Loei','northeast',false),
('TH-43','หนองคาย','Nong Khai','northeast',false),
('TH-44','มหาสารคาม','Maha Sarakham','northeast',false),
('TH-45','ร้อยเอ็ด','Roi Et','northeast',false),
('TH-46','กาฬสินธุ์','Kalasin','northeast',false),
('TH-47','สกลนคร','Sakon Nakhon','northeast',false),
('TH-48','นครพนม','Nakhon Phanom','northeast',false),
('TH-49','มุกดาหาร','Mukdahan','northeast',false),
('TH-50','เชียงใหม่','Chiang Mai','north',false),
('TH-51','ลำพูน','Lamphun','north',false),
('TH-52','ลำปาง','Lampang','north',false),
('TH-53','อุตรดิตถ์','Uttaradit','north',false),
('TH-54','แพร่','Phrae','north',false),
('TH-55','น่าน','Nan','north',false),
('TH-56','พะเยา','Phayao','north',false),
('TH-57','เชียงราย','Chiang Rai','north',false),
('TH-58','แม่ฮ่องสอน','Mae Hong Son','north',false),
('TH-63','ตาก','Tak','west',false),
('TH-70','ราชบุรี','Ratchaburi','west',false),
('TH-71','กาญจนบุรี','Kanchanaburi','west',false),
('TH-76','เพชรบุรี','Phetchaburi','west',false),
('TH-77','ประจวบคีรีขันธ์','Prachuap Khiri Khan','west',false),
('TH-80','นครศรีธรรมราช','Nakhon Si Thammarat','south',false),
('TH-81','กระบี่','Krabi','south',false),
('TH-82','พังงา','Phangnga','south',false),
('TH-83','ภูเก็ต','Phuket','south',false),
('TH-84','สุราษฎร์ธานี','Surat Thani','south',false),
('TH-85','ระนอง','Ranong','south',false),
('TH-86','ชุมพร','Chumphon','south',false),
('TH-90','สงขลา','Songkhla','south',false),
('TH-91','สตูล','Satun','south',false),
('TH-92','ตรัง','Trang','south',false),
('TH-93','พัทลุง','Phatthalung','south',false),
('TH-94','ปัตตานี','Pattani','south',false),
('TH-95','ยะลา','Yala','south',false),
('TH-96','นราธิวาส','Narathiwat','south',false)
on conflict (province_code) do update set
  province_name_th = excluded.province_name_th,
  province_name_en = excluded.province_name_en,
  region = excluded.region,
  is_unknown = excluded.is_unknown;
